routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'IndexController', 
        [
            'only' => ['index'],
            'names' => [
                'index' => 'home'
            ]
            ]);

Route::resource('portfolios', 'PortfolioController', 
      [
          'parameters' => [
              'portfolios' => 'alias'
          ]
      ]);

Route::resource('articles', 'ArticlesController',
        [
            'parameters' => [
                'articles' => 'alias'
            ]
        ]);

Route::get('articles/cat/{cat_alias?}', ['uses' => 'ArticlesController@index', 
    'as' => 'articlesCat'])->where('cat_alias', '[\w-]+');

Route::resource('comment', 'CommentController', ['only' => [
    'store'
]]);

Route::match(['get', 'post'], '/contacts', ['uses' => 'ContactsController@index', 'as' => 'contacts']);

//php artisan make:auth

Auth::routes();
//Route::get('login','Auth\LoginController@showLoginForm');

Route::post('login','Auth\LoginController@login');

Route::get('logout','Auth\LoginController@logout');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {
    Route::get('/',['uses' => 'Admin\AdminIndexController@index','as' => 'adminIndex']);
    Route::resource('/articles','Admin\ArticlesController');
});

resources/views/pink/404.blade.php
@extends(env('THEME').'.layouts.site')

@section('navigation')
{!! $navigation !!}
@endsection
@section('content')
<!-- START CONTENT -->
<div id="content-index" class="content group">
    <img class="error-404-image group" src="{{asset(env('THEME'))}}/images/features/404.png" title="Error 404" alt="404" />
    <div class="error-404-text group">
        <p>We are sorry but the page you are looking for does not exist.<br />You could <a href="index.html">return to the home page</a> or search using the search box below.</p>

    </div>
</div>
<!-- END CONTENT -->
@endsection

@section('footer')
@include(env('THEME').'.footer')
@endsection

resources/views/pink/article_content.blade.php
<div id="content-single" class="content group">
    <div class="hentry hentry-post blog-big group ">
        <!-- post featured & title -->
        
        @if($article)
        <div class="thumbnail">
            <!-- post title -->
            <h1 class="post-title"><a href="#">{{$article->title}}</a></h1>
            <!-- post featured -->
            <div class="image-wrap">
                <img src="{{asset(env('THEME'))}}/images/articles/{{$article->image->max}}" alt="00212" title="00212" />        
            </div>
            <p class="date">
                <span class="month">{{ $article->created_at->format('M')}}</span>
                <span class="day">{{ $article->created_at->format('d')}}</span>
            </p>
        </div>
        <!-- post meta -->
        <div class="meta group">
            <p class="author"><span>by <a href="#" title="{{$article->title}}" rel="author">{{$article->user->name}}</a></span></p>
            <p class="categories"><span>In: <a href="{{route('articlesCat', ['cat_alias'=>$article->category->alias ])}}" title="View all posts in {{$article->category->title}}" rel="category tag">{{$article->category->title}}</a></p>
            <p class="comments"><span><a href="#comments" title="Comment on This is the title of the first article. Enjoy it.">{{count($article->comments)?count($article->comments):0 }} {{ Lang::choice('content.comments', count($article->comments))}}</a></span></p>
        </div>
        <!-- post content -->
        <div class="the-content single group">
            <p>{!!$article->text!!}</p>
            <div class="socials">
                <h2>love it, share it!</h2>
                <a href="#" class="socials-small facebook-small" title="Facebook">facebook</a>
                <a href="#" class="socials-small twitter-small" title="Twitter">twitter</a>
                <a href="#" class="socials-small google-small" title="Google">google</a>
                <a href="#" class="socials-small pinterest-small" title="Pinterest">pinterest</a>
                <a href="#" class="socials-small bookmark-small" title="This is the title of the first article. Enjoy it.">bookmark</a>
            </div>
        </div>
        <p class="tags">Tags: <a href="#" rel="tag">book</a>, <a href="#" rel="tag">css</a>, <a href="#" rel="tag">design</a>, <a href="#" rel="tag">inspiration</a></p>
        <div class="clear"></div>
    </div>
    <!-- START COMMENTS -->
    <div id="comments">
        <h3 id="comments-title">
            <span>{{count($article->comments)}}</span> {{Lang::choice('content.comments', $article->comments)}}
        </h3>
        
        @set($com, $article->comments->groupBy('parent_id'))
        @if(count($article->comments) > 0)       
        <ol class="commentlist group">
            @foreach($com as $k => $comments)
                @if($k != null)
                    @break
                  @endif
                  
                  @include(env('THEME').'.comment', ['items' => $comments])
            @endforeach
            
      
  
        </ol>
        @endif
        <!-- START TRACKBACK & PINGBACK -->
        <h2 id="trackbacks">Trackbacks and pingbacks</h2>
        <ol class="trackbacklist"></ol>
        <p><em>No trackback or pingback available for this article.</em></p>

        <!-- END TRACKBACK & PINGBACK -->								
        <div id="respond">
            <h3 id="reply-title">Leave a <span>Reply</span> <small><a rel="nofollow" id="cancel-comment-reply-link" href="#respond" style="display:none;">Cancel reply</a></small></h3>
            <form action="{{route('comment.store')}}" method="post" id="commentform">
                @if(!Auth::check())
                <p class="comment-form-author"><label for="author">Name</label> <input id="name" name="name" type="text" value="" size="30" aria-required="true" /></p>
                <p class="comment-form-email"><label for="email">Email</label> <input id="email" name="email" type="text" value="" size="30" aria-required="true" /></p>
                <p class="comment-form-url"><label for="url">Website</label><input id="url" name="site" type="text" value="" size="30" /></p>
                @endif
                <p class="comment-form-comment"><label for="comment">Your comment</label><textarea id="comment" name="text" cols="45" rows="8"></textarea></p>
                <div class="clear"></div>
                <p class="form-submit">
                    <input id="comment_parent" type="hidden" name="comment_parent" value="0">
                    <input id="comment_post_ID" type="hidden" name="comment_post_ID" value="{{ $article->id}}">
                    {{ csrf_field() }}
                    <input name="submit" type="submit" id="submit" value="Post Comment" />
                </p>
            </form>
        </div>
        <!-- #respond -->
    </div>
    <!-- END COMMENTS -->
    @endif
</div>

resources/views/pink/comment.blade.php
  @foreach($items as $item)    
  <li id="li-comment-{{$item->id}}" class="comment even {{($item->user_id == $article->user_id)?'bypostauthor odd': ''}}">
      <div id="comment-{{$item->id}}"class="comment-container">
                    <div class="comment-author vcard">
                        @set($hash, isset($item->email)?md5($item->email):md5($item->user->email))
                        <img alt="" src="https://www.gravatar.com/avatar/{{$hash}}?d=mm&s=75" class="avatar" height="75" width="75" />
                        <cite class="fn">{{$item->user->name or $item->name}}</cite>                 
                    </div>
                    <!-- .comment-author .vcard -->
                    <div class="comment-meta commentmetadata">
                        <div class="intro">
                            <div class="commentDate">
                                <a href="#comment-2">
                                    {{is_object($item->created_at)?$item->created_at->format('F d, Y \a\t H:i' ):""}}</a>                        
                            </div>
                            <div class="commentNumber">#&nbsp;</div>
                        </div>
                        <div class="comment-body">
                            <p>{{$item->text}}</p>
                        </div>
                        <div class="reply group">
                            <a class="comment-reply-link" href="#respond" onclick="return addComment.moveForm(&quot;comment-{{$item->id}}&quot;, &quot;{{$item->id}}&quot;, &quot;respond&quot;, &quot;{{$item->article_id}}&quot;)">Reply</a>                    
                        </div>
                        <!-- .reply -->
                    </div>
                    <!-- .comment-meta .commentmetadata -->
                </div>
                <!-- #comment-##  -->
                
                @if(isset($com[$item->id]))
                    <ul class="children">
                        @include(env('THEME').'.comment', ['items' => $com[$item->id]])
                    </ul>
                @endif
            </li>
@endforeach

resources/views/pink/contact_bar.blade.php
<!-- START SIDEBAR -->

    <div class="widget-first widget contact-info">
        <h3>Contacts</h3>
        <div class="sidebar-nav">
            <ul>
                <li>
                    <i class="icon-map-marker" style="color:#979797;font-size:20pxpx"></i> Location: PinkRio, 115  Avenue street - Italy
                </li>
                <li>
                    <i class="icon-info-sign" style="color:#979797;font-size:20pxpx"></i> Phone: 3471717174
                </li>
                <li>
                    <i class="icon-print" style="color:#979797;font-size:20pxpx"></i> Fax: +39 0035 356 765
                </li>
                <li>
                    <i class="icon-envelope" style="color:#979797;font-size:20pxpx"></i> Email: pinkrio@yit.com
                </li>
            </ul>
        </div>
    </div>
    <div class="widget-last widget text-image">
        <h3>Customer Support</h3>
        <div class="text-image" style="text-align:left"><img src="images/callus.gif" alt="Customer Support" /></div>
        <p>Nunc sit amet pretium purus. Pellet netus et malesuada fames ac turpis egestas.entesque habitant morbi tristique senectus </p>
    </div>

<!-- END SIDEBAR -->

resources/views/pink/content.blade.php
@if($portfolios && count($portfolios)> 0)


<div id="content-home" class="content group">
				            <div class="hentry group">
				                <div class="section portfolio">
				                    
				                    <h3 class="title">{{trans('content.latest_projects') }}</h3>
				                    
				                    @foreach($portfolios as $k => $item)
				                    	
				                    	@if($k == 0) 
				                    		<div class="hentry work group portfolio-sticky portfolio-full-description">
				                        <div class="work-thumbnail">
				                            <a class="thumb"><img src="{{asset(env('THEME'))}}/images/projects/{{$item->image->max}}" alt="0081" title="0081" /></a>
				                            <div class="work-overlay">
				                                <h3><a href="{{route('portfolios.show', ['alias' => $item->alias])}}">{{$item->title}}</a></h3>
				                                <p class="work-overlay-categories"><img src="{{asset(env('THEME'))}}/images/categories.png" alt="Categories" /> in: <a href="#">{{$item->filter->title}}</a></p>
				                            </div>
				                        </div>
				                        <div class="work-description">
				                            <h2><a href="{{route('portfolios.show', ['alias' => $item->alias])}}">{{$item->title}}</a></h2>
				                            <p class="work-categories">in: <a href="#">{{$item->filter->title}}</a></p>
				                            <p>{{str_limit($item->text, 200)}}</p>
				                                <a href="{{route('portfolios.show', ['alias' => $item->alias])}}" class="read-more">|| Read more</a>
				                        </div>
				                    </div>
				                    
				                    <div class="clear"></div>
				                    		@continue
				                    	@endif
				                    
				                    
				                    @if($k == 1)
				                    <div class="portfolio-projects">
				                      @endif  
				                        <div class="related_project {{($k == 4)?' related_project_last': ''}}">
				                            <div class="overlay_a related_img">
				                                <div class="overlay_wrapper">
				                                    <img src="{{asset(env('THEME'))}}/images/projects/{{$item->image->mini}}" alt="0061" title="0061" />						
				                                    <div class="overlay">
				                                        <a class="overlay_img" href="{{asset(env('THEME'))}}/images/projects/{{$item->image->path}}" rel="lightbox" title=""></a>
				                                        <a class="overlay_project" href="{{route('portfolios.show', ['alias' => $item->alias])}}"></a>
				                                        <span class="overlay_title">{{$item->title}}</span>
				                                    </div>
				                                </div>
				                            </div>
				                            <h4><a href="{{route('portfolios.show', ['alias' => $item->alias])}}">{{$item->title}}</a></h4>
				                            <p>{{str_limit($item->text, 120)}}</p>
                                                        </div>
				                        
				                       @endforeach
				                    </div>
				                </div>
				                <div class="clear"></div>
				            </div>
				            <!-- START COMMENTS -->
				            <div id="comments">
				            </div>
				            <!-- END COMMENTS -->
				        </div>
				        
 @endif				       

resources/views/pink/content_one_comment.blade.php
<li id="li-comment-{{$data['id']}}" class="comment even borGreen">
    <div id="comment-{{$data['id']}}"class="comment-container">
        <div class="comment-author vcard">

            <img alt="" src="https://www.gravatar.com/avatar/{{$data['hash']}}?d=mm&s=75" class="avatar" height="75" width="75" />
            <cite class="fn">{{$data['name']}}</cite>                 
        </div>
        <!-- .comment-author .vcard -->
        <div class="comment-meta commentmetadata">
            <div class="intro">
                
                <div class="commentNumber">#&nbsp;</div>
            </div>
            <div class="comment-body">
                <p>{{$data['text']}}</p>
            </div>


        </div>

    </div>

</li>

resources/views/pink/customMenuItems.blade.php
@foreach($items as $item)

<li  {{ (URL::current() == $item->url()) ? "class=active" : '' }} >
    <a href="{{$item->url()}}">{{$item->title}}</a>
    @if($item->hasChildren())
    <ul class="sub-menu">
        @include(env('THEME').'.customMenuItems', ['items' => $item->children()])
    </ul>
    @endif
</li>
@endforeach

resources/views/pink/footer.blade.php
<div id="copyright">
                    <div class="inner group">
                        
                        <div class="right">
                            <a href="#" class="socials-small facebook-small" title="Facebook">facebook</a>
                            <a href="#" class="socials-small rss-small" title="Rss">rss</a>
                            <a href="#" class="socials-small twitter-small" title="Twitter">twitter</a>
                            <a href="#" class="socials-small flickr-small" title="Flickr">flickr</a>
                            <a href="#" class="socials-small skype-small" title="Skype">skype</a>
                            <a href="#" class="socials-small google-small" title="Google">google</a>
                            <a href="#" class="socials-small pinterest-small" title="Pinterest">pinterest</a>
                        </div>
                    </div>
                </div>

resources/views/pink/index.blade.php
@extends(env('THEME').'.layouts.site')


@section('navigation')
    {!! $navigation !!}
@endsection

@section('slider')
    {!! $sliders !!}
@endsection

@section('content')
    {!! $content !!}
@endsection

@section('bar')
    {!! $rightBar !!}
@endsection

@section('footer')
    {!! $footer !!}
@endsection

resources/views/pink/login.blade.php
@extends(env('THEME').'.layouts.site')

@section('content')
<div id="content-home" class="content group">
    <div class="hentry group">



        <form id="contact-form-contact-us" class="contact-form" method="POST" action="{{ url('/login') }}">

            {{ csrf_field() }}
            <fieldset>
                <ul>
                    <li class="text-field">
                        <label for="login">
                            <span class="label">Name</span>
                            <br />					<span class="sublabel">This is the name</span><br />
                        </label>
                        <div class="input-prepend"><span class="add-on"><i class="icon-user"></i></span><input type="text" name="login" id="login" class="required" value="" /></div>
                        @if ($errors->has('login'))
                        <span class="help-block">
                            <strong>{{ $errors->first('login') }}</strong>
                        </span>
                        @endif
                    </li>


                    <li class="text-field">
                        <label for="password">
                            <span class="label">Password</span>
                            <br />					<span class="sublabel">This is fiel for password</span><br />
                        </label>
                        <div class="input-prepend"><span class="add-on"><i class="icon-lock"></i></span><input type="password" name="password"  class="required" value="" /></div>
                        @if ($errors->has('password'))
                        <span class="help-block">
                            <strong>{{ $errors->first('password') }}</strong>
                        </span>
                        @endif
                    </li>
                    <li class="submit-button">

                        <input type="submit" name="yit_sendmail" value="Отправить" class="sendmail alignright" />			
                    </li>
                </ul>
            </fieldset>
        </form>
    </div>

</div>

@endsection

resources/views/pink/portfolio_content.blade.php
<!-- START CONTENT -->
<div id="content-page" class="content group">
    <div class="clear"></div>
    <div class="posts">
        <div class="group portfolio-post internal-post">
            
            @if($portfolio)
            
             <div id="portfolio" class="portfolio-full-description">

                <div class="fulldescription_title gallery-filters">
                    <h1>{{ $portfolio->title}}</h1>
                </div>

                <div class="portfolios hentry work group">
                    <div class="work-thumbnail">
                        <a class="thumb"><img src="{{ asset(env('THEME'))}}/images/projects/{{$portfolio->image->max}}" alt="0081" title="0081" /></a>
                    </div>
                    <div class="work-description">
                        <p> {{ $portfolio->text }} </p>
                        <div class="clear"></div>
                        <div class="work-skillsdate">
                            <p class="skills"><span class="label">Filter:</span> {{$portfolio->filter->title}}</p>
                            <p class="workdate"><span class="label">Customer:</span> {{$portfolio->customer}}</p>
                            <p class="workdate"><span class="label">Year:</span> {{$portfolio->created_at->format('Y')}}</p>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="clear"></div>
                 @if(!$portfolios->isEmpty())
                <h3>Other Projects</h3>

                <div class="portfolio-full-description-related-projects">
                   
                    @foreach($portfolios as $portfolio_item)
                         <div class="related_project">
                             
                            <a class="related_proj related_img" href="{{route('portfolios.show', ['alias' => $portfolio_item->alias])}}" title="Love"><img src="{{asset(env('THEME'))}}/images/projects/{{$portfolio_item->image->mini}}" alt="0061" title="0061" /></a>
                            <h4><a href="{{route('portfolios.show', ['alias' => $portfolio_item->alias])}}">{{$portfolio_item->title}}</a></h4>
                            
                         </div>
                    
                    
                    
                    @endforeach
                    

                </div>
                
                @endif
            </div>
            
            @endif
            
           
            <div class="clear"></div>
        </div>
    </div>
</div>
<!-- END CONTENT -->

resources/views/pink/portfolios.blade.php
@extends(env('THEME').'.layouts.site')

@section('navigation')
    {!! $navigation !!}
@endsection


@section('content')
    {!! $content !!}
@endsection

@section('footer')
    {!! $footer !!}
@endsection

resources/views/pink/portfolios_content.blade.php
<div id="content-page" class="content group">
    <div class="hentry group">
       <!-- <script>
            jQuery(document).ready(function ($) {
                $('.sidebar').remove();

                if (!$('#primary').hasClass('sidebar-no')) {
                    $('#primary').removeClass().addClass('sidebar-no');
                }

            });
        </script>-->
        
        @if($portfolios)
        <div id="portfolio" class="portfolio-big-image">

            @foreach($portfolios as $portfolio)
                   <div class="hentry work group">
                        <div class="work-thumbnail">
                            <div class="nozoom">
                                <img src="{{asset(env('THEME'))}}/images/projects/{{$portfolio->image->max}}" alt="0061" title="0061" />							
                                <div class="overlay">
                                    <a class="overlay_img" href="{{asset(env('THEME'))}}/images/projects/{{$portfolio->image->path}}" rel="lightbox" title="{{$portfolio->title}}"></a>
                                    <a class="overlay_project" href="{{route('portfolios.show', ['alias' => $portfolio->alias])}}"></a>
                                    <span class="overlay_title">{{$portfolio->title}}</span>
                                </div>
                            </div>
                        </div>
                        <div class="work-description">
                            <h3>{{$portfolio->title}}</h3>
                            <p>{!!$portfolio->text!!}</p>
                            <div class="clear"></div>
                            <div class="work-skillsdate">
                                <p class="skills"><span class="label">Filter:</span> {{$portfolio->filter->title}}</p>
                                <p class="workdate"><span class="label">Customer:</span> {{$portfolio->customer}}</p>
                                @if($portfolio->created_at)
                                
                                    <p class="workdate"><span class="label">Year:</span> {{$portfolio->created_at->format('Y')}}</p>
                                @endif
                                
                            </div>
                            <a class="read-more" href="{{route('portfolios.show', ['alias' => $portfolio->alias])}}">View Project</a>            
                        </div>
                        <div class="clear"></div>
                    </div>
            
            @endforeach
            <div class="general-pagination group">
             @if($portfolios->lastPage() > 1)
                                                    @if($portfolios->currentPage() !== 1)
                                                        <a href="{{ $portfolios->url($portfolios->currentPage() - 1)}}" >{{ Lang::get('pagination.previous') }}</a>
                                                    @endif
                                                    
                                                    @for($i = 1; $i <= $portfolios->lastPage(); $i++)
                                                        @if($portfolios->currentPage() == $i)
                                                            <a  class="selected disabled">{{$i}}</a>
                                                         @else
                                                            <a href="{{$portfolios->url($i)}}">{{$i}}</a>
                                                         @endif
                                                    @endfor
                                                    @if($portfolios->currentPage() !== $portfolios->lastPage())
                                                         <a href="{{ $portfolios->url($portfolios->currentPage() + 1)}}">{{ Lang::get('pagination.next') }}</a>
                                                    @endif
                                                @endif
            </div>
        </div>
        @endif
        <div class="clear"></div>
    </div>
    
</div>

resources/views/pink/rightbar.blade.php
<div class="sidebar group">
    
    {!!$content_rightBar!!}
    
</div>